import { Inter, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/header';

const inter = Inter({
	subsets: ['latin', 'cyrillic'],
	display: 'swap',
	variable: '--font-inter',
});

const jetbrainMono = JetBrains_Mono({
	subsets: ['latin', 'cyrillic'],
	display: 'swap',
	variable: '--font-mono',
});

export const metadata = {
	title: 'DevSquad',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en' className={`${inter.className} h-full antialiased`}>
			<body className='min-h-full bg-background text-white flex flex-col'>
				<Header />
				{children}
			</body>
		</html>
	);
}
